### ISSUE TITLE
Notify delay fails in chefspec

### ISSUE THREAD

**Issue by bclow-invoca** [chef-cookbooks/compat_resource#102]
### Cookbook version
12.13.37, 12.13.38, 12.14.0, 12.14.1, 12.14.2

### Chef-client version
12.11.18

### Platform Details
ubuntu 14.04, chefspec 4.7.0

### Scenario:
Cookbook calls service notify with restart/start and delay. Chefspec test verifies restart/start gets called with delay.

### Steps to Reproduce:
Cookbook resource is updated, uses notify to restart/start a service with a delay. The chefspec test then tests to verify the recipe functions as expected.

### Expected Result:
The chefspec test will pass.

### Actual Result:
The test fails. Example error from one of our cookbooks:

```
     Failure/Error: expect(chef_run.find_resource(:consul_service, 'consul')).to subscribe_to('consul_config[consul]').on(:restart).delayed

       expected "consul_config[consul]" to notify "consul_service[consul]" with action :restart delayed, but did not.

       Other notifications were:



     # ./test/unit/chefspec/server_install_spec.rb:82:in `block (2 levels) in <top (required)>'
```

**Comment by lamont-granquist** [comment]
most likely the same bug as #99

**Comment by lamont-granquist** [comment]
is it actually failing in the chef run or is it only chefspec failing to match it even though the cookbook is working fine?

**Comment by lamont-granquist** [comment]
be useful to test this on the 12.14.3 release and see if its still broken or not

**Comment by bclow-invoca** [comment]
I will be testing momentarily.

**Comment by bclow-invoca** [comment]
That update appears to have fixed the issues we were having with our cookbooks. Thank you.
