### ISSUE TITLE
Chef::Log.caller_location patch is both broken and not needed on most Chef versions

### ISSUE THREAD

**Issue by coderanger** [chef-cookbooks/compat_resource#115]
So part one, it is currently using `Gem.loaded_specs['chef'].full_gem_path`, the right-er code (I think) is `::File.join(::Gem::Specification.find_by_name('chef').gem_dir, 'lib')` (or at least that's what I use in Poise for a similar purpose and it hasn't exploded yet). Currently this can fail if chef isn't in `loaded_specs` due to gem or bundler hilarity.

Second, it looks like that method shipped in Chef 12.6, so the patch should probably be conditional on the Chef version to start with.

**Comment by lamont-granquist** [comment]
Can we just patch old chef-client versions with whatever the latest code is?  That's the tactic that I've been switching to, with this being the main conditional I'm going to lean on:

https://github.com/chef-cookbooks/compat_resource/blob/master/libraries/autoload.rb#L16-L17

That is basically "we can't predict the future, so lets not monkeypatch it, and it should do what we want anyway"

While monkeypatching over identical code should be a no-op.  That way we don't have to maintain a pile of chef-client conditionals for when each feature was introduced.  Convergent, but not necessarily idempotent monkeypatching...

**Comment by coderanger** [comment]
That just makes it much harder to know how to debug anything ever. I'm already not a fan of this cookbook and that makes it 10x worse. We should be patching _fewer_ things in here over time, not more. The original goal was tightly scoped and applied to very specific features, this has in time mutated in to both something depended on by almost every cookbook Chef Software maintains and also pretty much a monkeypatch for every new feature in Chef related to resources. We need to stop doing this, it's ruining all hope for debugging being sane going forward.

**Comment by lamont-granquist** [comment]
unlikely to get fixed before we stop using this cookbook completely
