### ISSUE TITLE
Refresh resources with latest/last Chef 12 resource states

### ISSUE THREAD

**Issue by iancward** [chef-cookbooks/compat_resource#130]
### Cookbook version
12.16.3

### Chef-client version
12.13.37-1

### Platform Details
RHEL7

### Scenario:
It looks like Chef 13 is GA now, so it might be time to refresh this repository with the latest/last Chef 12 resource code.

We have a bit of a conundrum with the yum resource that refreshing this cookbook should address.
We're currently running chef client 12.13.37 (newer client versions have issues with minitests, which we are working on moving off of in favor of InSpec).

We have a cookbook that wraps a number of yum cookbooks, which used to depend on the https://github.com/chef-cookbooks/yum cookbook, which had an issue in that it did not properly flush metadata cache prior to repo deletion. 
This issue is important to us due to the number of repositories we use and especially because of the enormous size of the yum-chef-stable repo metadata (I have a support case open with Chef on this).

The cache deletion issue was fixed in https://github.com/chef-cookbooks/yum/pull/166, which was released with yum cookbook version 4.1.0. However, code from before the fix was migrated to chef client version 12.14. The current yum repo cookbooks now depend on this (compat_resource) cookbook; however, the resource code is from version 12.16.3 and https://github.com/chef/chef/pull/5509 didn't get released until chef client version 12.17.44.

**Comment by tas50** [comment]
We can't entirely update compat_resource for Chef 12.19 due to a pile of extra code we'd have to backport. I have opened a PR that plucks the apt/yum changes that occurred. https://github.com/chef-cookbooks/compat_resource/pull/131

**Comment by tas50** [comment]
12.19.0 is out
