### ISSUE TITLE
Link to slides in README is 403

### ISSUE THREAD

**Issue by wohali** [chef-cookbooks/compat_resource#132]
Hi there,

The link to the Slides in your README (https://docs.chef.io/decks/custom_resources.html) is returning a 403. Can this be fixed? Thanks!

**Comment by tas50** [comment]
@wohali If you could open a PR to update the readme I'd gladly merge it

**Comment by wohali** [comment]
I don't know where the slides moved to :D I'd love to open a PR if I did. I think this needs help from someone @ Chef themselves.

**Comment by tas50** [comment]
We've nuked them from the readme
