### ISSUE TITLE
No .supermethod error, chef 12.5.1, compat_resources 12.5.13

### ISSUE THREAD

**Issue by kpmueller** [chef-cookbooks/compat_resource#15]
- compat_resource (12.5.13)

================================================================================
  Recipe Compile Error in /var/chef/cache/cookbooks/role_build/recipes/default.rb
  ================================================================================

  NoMethodError
  -------------
  undefined method `super_method' for #<Method: Class(Chef::ChefCompatDeprecation)#log_deprecation>

  Cookbook Trace:
  ---------------
    /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef.rb:6:in `log_deprecation'
    /var/chef/cache/cookbooks/python/recipes/pip.rb:52:in `block in from_file'
    /var/chef/cache/cookbooks/python/recipes/pip.rb:50:in `from_file'
    /var/chef/cache/cookbooks/python/recipes/default.rb:22:in `from_file'
    /var/chef/cache/cookbooks/piazza_base/recipes/_python.rb:11:in `from_file'
    /var/chef/cache/cookbooks/piazza_base/recipes/default.rb:20:in `from_file'
    /var/chef/cache/cookbooks/role_build/recipes/default.rb:4:in `from_file'

  Relevant File Content:
  ----------------------
  /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef.rb:

    1:  class Chef
    2:    NOT_PASSED = Object.new if !defined?(NOT_PASSED)
    3:    # Earlier versions of Chef didn't have this message
    4:    module ChefCompatDeprecation
    5:      def log_deprecation(message, location=nil)
    6>>       if method(:log_deprecation).super_method
    7:          if !location
    8:            # Pick the first caller that is *not* part of the Chef or ChefCompat gem,
    9:            # that's the thing the user wrote.
   10:            chef_compat_gem_path = File.expand_path("../../..", __FILE__)
   11:            chef_gem_path = File.expand_path("../..",::Chef::Resource.instance_method(:initialize).source_location[0])
   12:            caller(0..10).each do |c|
   13:              if !c.start_with?(chef_gem_path) && !c.start_with?(chef_compat_gem_path)
   14:                location = c
   15:                break

  Running handlers:
[2015-11-03T13:50:16-08:00] ERROR: Running exception handlers
  Running handlers complete
[2015-11-03T13:50:16-08:00] ERROR: Exception handlers complete
  Chef Client failed. 0 resources updated in 02 seconds
[2015-11-03T13:50:16-08:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
[2015-11-03T13:50:16-08:00] ERROR: undefined method `super_method' for #<Method: Class(Chef::ChefCompatDeprecation)#log_deprecation>
[2015-11-03T13:50:17-08:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)

**Comment by ThatsNinja** [comment]
:+1:

Mine's being raised from within the New Relic cookbook:
```
192.168.16.193 Cookbook Trace:
192.168.16.193 ---------------
192.168.16.193   /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef.rb:6:in `log_deprecation'
192.168.16.193   /var/chef/cache/cookbooks/newrelic/resources/agent_nodejs.rb:15:in `class_from_file'
192.168.16.193   /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/resource/lwrp_base.rb:50:in `build_from_file'
```

Full output of my `NoMethod` error:
```
192.168.16.193 NoMethodError
192.168.16.193 -------------
192.168.16.193 undefined method `super_method' for #<Method: Class(Chef::ChefCompatDeprecation)#log_deprecation>
```
`Relevant File Content` is the same.

**Comment by scalp42** [comment]
Same thing here:

```
    amazon-ebs: ================================================================================
    amazon-ebs: Recipe Compile Error in /var/chef/cache/cookbooks/gz-papertrail/resources/monitor.rb
    amazon-ebs: ================================================================================
    amazon-ebs:
    amazon-ebs: NoMethodError
    amazon-ebs: -------------
    amazon-ebs: undefined method `super_method' for #<Method: Class(Chef::ChefCompatDeprecation)#log_deprecation>
    amazon-ebs:
    amazon-ebs: Cookbook Trace:
    amazon-ebs: ---------------
    amazon-ebs: /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef.rb:6:in `log_deprecation'
    amazon-ebs: /var/chef/cache/cookbooks/gz-papertrail/resources/monitor.rb:16:in `class_from_file'
    amazon-ebs: /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/resource/lwrp_base.rb:50:in `build_from_file'
    amazon-ebs:
    amazon-ebs: Relevant File Content:
    amazon-ebs: ----------------------
    amazon-ebs: /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef.rb:
    amazon-ebs:
    amazon-ebs: 1:  class Chef
    amazon-ebs: 2:    NOT_PASSED = Object.new if !defined?(NOT_PASSED)
    amazon-ebs: 3:    # Earlier versions of Chef didn't have this message
    amazon-ebs: 4:    module ChefCompatDeprecation
    amazon-ebs: 5:      def log_deprecation(message, location=nil)
    amazon-ebs: 6>>       if method(:log_deprecation).super_method
    amazon-ebs: 7:          if !location
    amazon-ebs: 8:            # Pick the first caller that is *not* part of the Chef or ChefCompat gem,
    amazon-ebs: 9:            # that's the thing the user wrote.
    amazon-ebs: 10:            chef_compat_gem_path = File.expand_path("../../..", __FILE__)
    amazon-ebs: 11:            chef_gem_path = File.expand_path("../..",::Chef::Resource.instance_method(:initialize).source_location[0])
    amazon-ebs: 12:            caller(0..10).each do |c|
    amazon-ebs: 13:              if !c.start_with?(chef_gem_path) && !c.start_with?(chef_compat_gem_path)
    amazon-ebs: 14:                location = c
    amazon-ebs: 15:                break
```

cc @jkeiser

**Comment by andrefreitas** [comment]
I am using 12.5.13 and have the same error:
```
Error executing action `install` on resource 'python_pip[virtualenv]'
staging-nlife.ndrive.com     ================================================================================
staging-nlife.ndrive.com
staging-nlife.ndrive.com     NoMethodError
staging-nlife.ndrive.com     -------------
staging-nlife.ndrive.com     undefined method `super_method' for #<Method: Class(Chef::ChefCompatDeprecation)#log_deprecation>
staging-nlife.ndrive.com
staging-nlife.ndrive.com     Cookbook Trace:
staging-nlife.ndrive.com     ---------------
staging-nlife.ndrive.com     /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef.rb:6:in `log_deprecation'
staging-nlife.ndrive.com     /var/chef/cache/cookbooks/python/providers/pip.rb:98:in `load_current_resource'
staging-nlife.ndrive.com
staging-nlife.ndrive.com     Resource Declaration:
staging-nlife.ndrive.com     ---------------------
staging-nlife.ndrive.com     # In /var/chef/cache/cookbooks/ndrive-web/recipes/python_app.rb
staging-nlife.ndrive.com
staging-nlife.ndrive.com       6: python_pip "virtualenv"
staging-nlife.ndrive.com
staging-nlife.ndrive.com     Compiled Resource:
```
Sad not beeing able to close a sprint due this constant issues.

**Comment by jkeiser** [comment]
Hey everyone, I've released 12.5.14 which I believe fixes this issue for good. Can you please give it a spin?

**Comment by lamont-granquist** [comment]
fixed in 12.5.14

**Comment by kpmueller** [comment]
Looks good here - thanks for the fix!

**Comment by ThatsNinja** [comment]
:+1: for the fix. thanks, @jkeiser, @lamont-granquist!
