### ISSUE TITLE
when this is pulled in for deps, it kills chef run

### ISSUE THREAD

**Issue by spheromak** [chef-cookbooks/compat_resource#17]
Instead of being hostile to chef 11 runs it should just not provide the functionality.  Using multipackage  depends on compat_resource, and compat_resource is failing chef runs on chef11

**Comment by eduherraiz** [comment]
+1 Using Amazon opsworks here. This system don't provide a way to upgrade to Chef 12.
A older cookbok docker has the dependency:
```compat_resource >= 0.0.0```
and I can't found the correct version dependency on your cookbook. :-(
I just only now my docker's cookbook is from November 2014. 
There is any way to get a compat_resource cookbook from this date?

**Comment by mwjackson** [comment]
+1 We also see this error

================================================================================
Recipe Compile Error in /var/lib/aws/opsworks/cache.stage2/cookbooks/compat_resource/libraries/autoload.rb
================================================================================
 
 
RuntimeError
------------
The compat_resources cookbook does not support chef versions older than Chef 12.0.0
 
 
Cookbook Trace:
---------------
/var/lib/aws/opsworks/cache.stage2/cookbooks/compat_resource/libraries/autoload.rb:2:in `<top (required)>'

**Comment by eduherraiz** [comment]
We found a solution for our problem with opsworks. Was the cookbok iptables.
Fixing iptables to 1.0.0 in Berksfile solves it

**Comment by mwjackson** [comment]
We also ended up pinning rsyslog <= 2.2.0 which has solved the problem for now

**Comment by benholtz** [comment]
All of our chef runs now fail. "The compat_resources cookbook does not support chef versions older than Chef 12.0.0"
Looks like it started here... https://github.com/chef-cookbooks/compat_resource/commit/386bbc465c3e4a46eac82ce911251860f5d5b747
 What a headache.

**Comment by lamont-granquist** [comment]
All of the cookbooks that use compat_resource have had major version bumps to indicate breaking changes and have dropped support for Chef 11.

This cookbook is operating as designed.  It does not and will not support Chef 11.  Cookbooks written to use compat_resource are written with Chef 12.5.x syntax and with this cookbook will only work on Chef 12.0-12.5

Chef 11 users MUST pin their cookbook to prior major revisions.  Pinning with a '~>' operator is best-practice anyway.

**Comment by lamont-granquist** [comment]
It was pointed out to me that this was breaking people who were pulling a cookbook they didn't use which then depended upon compat_resource.

So I moved where the exception occurs in #18 

However, I suspect that this will not fix anyone's chef client runs.  Since the cookbook people don't use has Chef 12.5 resources in them all those files will always get parsed and the Chef::Resource.action method will always get called.

At least that way it does blow up with a pointer to the code upstream from this cookbook which is written in 12.5 resources style which cannot run on 11.x
