### ISSUE TITLE
converge_by not outputting all modified properties

### ISSUE THREAD

**Issue by chasebolt** [chef-cookbooks/compat_resource#19]
sometimes I get output of `"update #{current_resource.identity}"`but with no entries outputted from the `modified` array. if I put a `puts ''` immediately after the converge_by block, it will output **most** of the modified array but still not all of it.

here are 2 gists showing the issue. i simply added `puts "\n\nchase: modified is: #{modified}"` at line 51 https://github.com/chef-cookbooks/compat_resource/blob/master/files/lib/chef_compat/copied_from_chef/chef/provider.rb#L50-L51

https://gist.github.com/chasebolt/a75ecbe829fe6dfa1be5
https://gist.github.com/chasebolt/66b5d4fb76c8eb2b6a12

you can see on this line that modified holds modified properties, but did not output it. https://gist.github.com/chasebolt/a75ecbe829fe6dfa1be5#file-gistfile1-txt-L277-L283

**Comment by jkeiser** [comment]
This has a fix, taken in from chef. Will check that in soon.

**Comment by jkeiser** [comment]
Oh, never mind. I read that wrong. Will investigate.

**Comment by chasebolt** [comment]
I have a branch of docker that is currently experiencing this issue. You can run test-kitchen resources-191-ubuntu-1504 multiple times, after the 2nd run you will see a couple of resources updated but it doesnt output why they were updated.

https://github.com/chasebolt/chef-docker/tree/output-format-issue

**Comment by lamont-granquist** [comment]
since this is 6 months old and a ton has changed in this cookbook since then, i'm unfortunately just going to close this assuming it got fixed at some point.

if not, please cut a new issue.
