### ISSUE TITLE
Undefined method full_gem_path

### ISSUE THREAD

**Issue by ChestersGarage** [chef-cookbooks/compat_resource#35]
Hello,

Not sure what to make of this error, and I can't get past it.

(Amazon Linux AMI release 2015.09)

================================================================================
Recipe Compile Error in /var/chef/cache/cookbooks/compat_resource/libraries/autoload.rb
================================================================================

NoMethodError
-------------
undefined method `full_gem_path=' for #<Gem::Specification:0x1ac1bc8 ->

Cookbook Trace:
---------------
  /var/chef/cache/cookbooks/compat_resource/files/lib/compat_resource/gemspec.rb:10:in `block in <module:CompatResource>'
  /var/chef/cache/cookbooks/compat_resource/files/lib/compat_resource/gemspec.rb:8:in `new'
  /var/chef/cache/cookbooks/compat_resource/files/lib/compat_resource/gemspec.rb:8:in `<module:CompatResource>'
  /var/chef/cache/cookbooks/compat_resource/files/lib/compat_resource/gemspec.rb:7:in `<top (required)>'
  /var/chef/cache/cookbooks/compat_resource/libraries/autoload.rb:15:in `require_relative'
  /var/chef/cache/cookbooks/compat_resource/libraries/autoload.rb:15:in `<top (required)>'

Relevant File Content:
----------------------
/var/chef/cache/cookbooks/compat_resource/files/lib/compat_resource/gemspec.rb:

  3:  end
  4:
  5:  require_relative 'version'
  6:
  7:  module CompatResource
  8:    GEMSPEC = Gem::Specification.new do |s|
  9:      # Gem path is cookbook root
 10>>     s.full_gem_path = File.expand_path('../../../..', __FILE__)
 11:      s.name = "compat_resource"
 12:      s.version = CompatResource::VERSION
 13:      s.platform = Gem::Platform::RUBY
 14:      s.summary = 'Bring some new features of Chef 12.5 to previous 12.X releases'
 15:      s.description = s.summary
 16:      s.author = 'John Keiser'
 17:      s.email = 'john@johnkeiser.com'
 18:      s.homepage = 'http://chef.io'
 19:      s.license = 'Apache 2.0'

**Comment by viyh** [comment]
+1

**Comment by lmunro** [comment]
+1

**Comment by mburns** [comment]
+1

**Comment by adickel1** [comment]
Any ideas here on what is causing this?

I'm guessing its supposed to expand to the dir 4 levels beneath it, for me thats the base cookbook dir , what else is this even looking for?

**Comment by PaulTurner-awin** [comment]
+1

**Comment by saranicole** [comment]
I had this issue and resolved it by upgrading my version of Chef from Chef 11 to Chef 12.

Take a look at this thread:
https://github.com/chef/chef/issues/3915 

@martinb3 posts:
"This bug affects chef-client versions using a style of resource/provider from Chef < 12.x, so it shouldn't be affecting anyone on the 12.x.x versions (released almost a full 12 months ago). "

Running the chef cookbook compat_resource with Chef 11 I got:
	undefined method `full_gem_path=' for #<Gem::Specification name= version=>

With Chef 12 it runs fine.

So to fix ...

On CentOs:
yum remove -y chef

then:
curl -L https://www.opscode.com/chef/install.sh | bash
(or your preferred installation method)

**Comment by adickel1** [comment]
setting my cookbook to utilize chef 12.5.1 instead of 11.x resolved the issue for me.

**Comment by pjelar** [comment]
I tried 12.5.1 but still no luck. +1

**Comment by pjelar** [comment]
I fixed this by reverting to an older version

`cookbook 'compat_resource', "12.5.14"`

**Comment by martinb3** [comment]
From the first sentence in the readme:
> This cookbook brings the custom resource syntax from Chef 12.5 to earlier Chef 12.X releases.

I don't think this cookbook is intended at all for Chef 11.x, so I'm not surprised that was a fix for some folks.

**Comment by hoitomt** [comment]
This issue is due to an old version of Rubygems being installed on the target box to which you are deploying. A Chef upgrade fixes the issue. However another solution would be to upgrade the version of Rubygems on the target box to something on or after 2.2.0.rc1 (https://github.com/rubygems/rubygems/commit/d213a8083dc09380601a270d1e771476cb67e7fc)

**Comment by bemehow** [comment]
The `compat_resource` cookbook is pulled by the `rsyslog > 2.2.0` if you want to keep the Chef 11 runtime you should pin the rsyslog to that version in your Berksfile.

```
❯ cat Berksfile
source 'https://supermarket.chef.io'

metadata
# compat_resource <- rsyslog <- bluepill <- nginx
# anything abote 2.2.0 is not compatible with Chef 11
cookbook 'rsyslog', '= 2.2.0'
```

**Comment by icberg7** [comment]
I'm getting this error on Chef 12.8.1.
12.8.1 is the only version of chef installed, and this server does not have a local ruby installed at all.

**Comment by icberg7** [comment]
I uninstalled chef 12.8.1, deleted /var/chef and /opt/chef and then re-installed chef 12.8.1 and chef appears to be running now.

**Comment by icberg7** [comment]
My host that was working yesterday is failing on the `full_gem_path` issue again.

**Comment by icberg7** [comment]
So while working on this, I realized I had a cookbook that was changing the rubygems version by running `gem update --system` and it was apparently downgrading the version of rubygems to 2.1.9. Chef 12.8.1 uses 2.5.2 
Once I removed this recipe from the runlist and re-installed chef, I've been able to get multiple successful runs in.

**Comment by danieljimenez** [comment]
Failing here too.

**Comment by lamont-granquist** [comment]
The version of rubygems in Chef 12.0.3 is 2.4.1 which supports the full_gem_path API.

QED everyone hitting this problem must be using Chef 11.

(or it seems that one person might be having a cookbook run a gem update --system to /downgrade/ the version of rubygems to 2.1.9 which is is not something that we'd ever support).

So, apologies, but the cookbook that you're trying to run that depends on this cookbook has decided to drop support for Chef 11.x completely.

You must pin to your own deps to a prior version of that cookbook which at a minimum does not have a dependency on compat_resource and/or upgrade to Chef 12.

There is no bug to fix in this repo, its working as intended.

The error message is, admittedly, quite fantastically shitty, but probably the best solution for that is to support the chef_version cookbook metadata better everywhere, but you'll only get that by upgrading so its a bit of a catch-22.
