### ISSUE TITLE
property_is_set? not behaving as expected

### ISSUE THREAD

**Issue by someara** [chef-cookbooks/compat_resource#36]
I'm getting "false" where I would expect "true"... am I using this incorrectly?

recipe - https://github.com/chef-cookbooks/docker/blob/7af68dc4deae355e1bbccefb1266dea1544ceb07/test/cookbooks/docker_test/recipes/container.rb#L450

coerce method - https://github.com/chef-cookbooks/docker/blob/7af68dc4deae355e1bbccefb1266dea1544ceb07/libraries/helpers_container.rb#L5

spec - https://github.com/chef-cookbooks/docker/blob/master/spec/docker_test/container_spec.rb#L421

failure - https://travis-ci.org/chef-cookbooks/docker/builds/99784948#L349

**Comment by lamont-granquist** [comment]
since `coerce_hostname` got removed i'm guess that was not the way to use it...  looks like a roundabout way of writing a lazy default or something...
