### ISSUE TITLE
cannot load such file

### ISSUE THREAD

**Issue by cyberflow** [chef-cookbooks/compat_resource#38]
Cookbook Trace:
       ---------------
         /tmp/kitchen/cache/cookbooks/compat_resource/libraries/autoload.rb:15:in `require_relative'
         /tmp/kitchen/cache/cookbooks/compat_resource/libraries/autoload.rb:15:in `<top (required)>'

       Relevant File Content:
       ----------------------
       /tmp/kitchen/cache/cookbooks/compat_resource/libraries/autoload.rb:

         8:    cookbook_version = $1
         9:
        10:    if CompatResource::VERSION != cookbook_version
        11:      raise "compat_resource gem version #{CompatResource::VERSION} was loaded as a gem before compat_resource cookbook version #{cookbook_version} was loaded. To remedy this, either update the cookbook to the gem version, update the gem to the cookbook version, or uninstall / stop loading the gem so early."
        12:    end
        13:  else
        14:    # The gem is not already activated, so activate the cookbook.
        15>>   require_relative '../files/lib/compat_resource/gemspec'
        16:    CompatResource::GEMSPEC.activate
        17:  end
        18:
        19:  require 'compat_resource'
        20:

**Comment by MichaelDowse** [comment]
@cyberflow What was the resolution here? I'm having the same issue.

**Comment by cyberflow** [comment]
@MichaelDowse I change chef-client version to 12.X.

**Comment by MichaelDowse** [comment]
Indeed my issue was that one of my cookbooks had become dependent on chef-client >= 12 while I wasn't looking. I fixed the issue for now by locking `apt` at version 2.9.2

**Comment by micahwedemeyer** [comment]
I had a similar problem with the `build-essential` package and was able to fix the issue by downgrading it. Basically, if you're not on Chef 12, any package that depends on `compat_resource` needs to be downgraded back to a point where it doesn't depend on `compat_resource`

You can check the dependencies and old versions on supermarket.chef.io
