### ISSUE TITLE
Incorrect warning thrown when using LWRP DSL

### ISSUE THREAD

**Issue by someara** [chef-cookbooks/compat_resource#40]
The yum cookbook still uses the LWRP DSL. 

https://github.com/chef-cookbooks/yum/blob/5bbae401021264dd549310590e5612640d41eddf/resources/globalconfig.rb#L77

When using Chef 12.6.1, it throws this warning

Deprecated features used!
  Cannot specify both default and name_property together on property path of resource yum_globalconfig. Only one (name_property) will be obeyed. In Chef 13, this will become an error. at 1 location:
    - /opt/kitchen/cache/cookbooks/yum/resources/globalconfig.rb:76:in `class_from_file'

**Comment by lamont-granquist** [comment]
pretty certain this was a bug in core chef's deprecation was was fixed there and has almost certainly been pulled into this cookbook....
