### ISSUE TITLE
cannot load such file -- chef_compat - chef_client 12.7.2

### ISSUE THREAD

**Issue by amodpandey** [chef-cookbooks/compat_resource#47]
Compiling Cookbooks...

================================================================================
Recipe Compile Error in /var/chef/cache/cookbooks/compat_resource/libraries/autoload.rb
================================================================================

LoadError
---------
cannot load such file -- chef_compat

Cookbook Trace:
---------------
 /var/chef/cache/cookbooks/compat_resource/libraries/autoload.rb:12:in `<top (required)>'

Relevant File Content:
----------------------
/var/chef/cache/cookbooks/compat_resource/libraries/autoload.rb:

 5:  begin
 6:    compat_resource_gem = Gem::Specification.find_by_name("compat_resource")
 7:  rescue Gem::LoadError
 8:  end
 9:  
10:  if compat_resource_gem
11:    # The gem is installed.
12>>   require 'chef_compat'

Worked fine after chef-client downgrade to 12.4.0. Also works on 12.5.1

The dependency is brought by iptables
- iptables
  - compat_resource

**Comment by amodpandey** [comment]
iptables@2.0.1, compat_resource@12.5.14

**Comment by jkeiser** [comment]
It's probably a good idea to just bring in the latest compat_resource
(12.9.0), using a downgraded compat resource on a later chef is a generally
bad idea.

**Comment by drahamim** [comment]
this occurs for me on compat_resource 12.9.1
