### ISSUE TITLE
Recipe Compile Error in /var/chef/cache/cookbooks/compat_resource/libraries/autoload.rb

### ISSUE THREAD

**Issue by sanketgawade** [chef-cookbooks/compat_resource#5]
Can anyone help me with this. Our internal recipes are failing due some update of dependencies.

10-23 10:42:21 INFO whe71b-graphite-1: ================================================================================
10-23 10:42:21 INFO whe71b-graphite-1: Recipe Compile Error in /var/chef/cache/cookbooks/compat_resource/libraries/autoload.rb
10-23 10:42:21 INFO whe71b-graphite-1: ================================================================================
10-23 10:42:21 INFO whe71b-graphite-1: LoadError
10-23 10:42:21 INFO whe71b-graphite-1: ---------
10-23 10:42:21 INFO whe71b-graphite-1: cannot load such file -- chef_compat
10-23 10:42:21 INFO whe71b-graphite-1: Cookbook Trace:
10-23 10:42:21 INFO whe71b-graphite-1: ---------------
10-23 10:42:21 INFO whe71b-graphite-1:   /var/chef/cache/cookbooks/compat_resource/libraries/autoload.rb:21:in `<top (required)>'

**Comment by andrewjamesbrown** [comment]
I'm able to reproduce this with chef-client 11.x, but not with chef-client 12.x.  It would be nice if this cookbook was backwards compatible with 11.x as well, even if it was a no-op.

**Comment by ARentz07** [comment]
I am seeing the same issue in chef-client 11.18.12, but I don't see it in 12. Was the previous release compatible with 11?

**Comment by sanketgawade** [comment]
@andrewjamesbrown @ARentz07 
I found that iptables 2.0.0 cookbook release caused this. I pinned our cookbook to use iptables 1.1.0 and it all works again.

https://github.com/chef-cookbooks/iptables/releases/tag/v2.0.0

**Comment by josephsiefers** [comment]
@sanketgawade Thanks so much...your solution worked for me!

**Comment by bhanushrestha** [comment]
@sanketgawade  could you please walk me through on how you pinned the cookbook to use iptables 1.1.0 cause i keep getting similar error . Thank you

**Comment by fsav** [comment]
@bhanushrestha I had the same problem and adding this line in metadata.rb (following what @sanketgawade suggested) seems to have fixed it for me:

depends 'iptables', '= 1.1.0'

(I was not directly including iptables, but I think it's included indirectly through the apache2 cookbook)

**Comment by sanketgawade** [comment]
@bhanushrestha yes that right what @fsav suggested.

**Comment by bottkv488** [comment]
@sanketgawade +1 for your comment, saved me a *lot* of time, as I read this 5 minutes after the issue hit me :)

@ALL: You might consider putting the version constraint into your environment, but keep in mind that this applies to all member nodes/cookbooks

**Comment by bhanushrestha** [comment]
Thanks a ton @fsav  and @sanketgawade . It worked and really helped after spending much part of a day scratching my head over what was going on.

**Comment by lamont-granquist** [comment]
This cookbook can't be made back-compat with chef 11.x by turning it into a no-op.

**Comment by andrewjamesbrown** [comment]
@lamont-granquist why not?  `node['chef_packages']['chef']['version']` can be parsed and logic added to do something different if we detect chef 11.x is installed.  Am I missing something?

**Comment by lamont-granquist** [comment]
This cookbook fundamentally back-ports chef 12.5 resources into a cookbook so that chef 12.0-12.4 can use that syntax in their resource definitions.  It doesn't work on Chef 11.  If we no-op'd this cookbook on chef 11, then the cookbook which depended on this will throw an exception when the parser hits 12.5 resource DSL statements like 'action' in the resources file.

**Comment by gomteshhatginecognologix** [comment]
Even Facing problem:

cookbook 'jenkins', '= 2.4.0'
cookbook 'iptables', '= 1.1.0'
cookbook 'apt', '~> 3.0.0'
cookbook 'build-essential', '~> 3.2.0'
