### ISSUE TITLE
Upgrading from 12.9.1 -> 12.10.1 breaks other cookbooks, eg. "apt"

### ISSUE THREAD

**Issue by rmoriz** [chef-cookbooks/compat_resource#54]
### Cookbook version
12.10.1

### Chef-client version
12.8.1

### Platform Details
Debian 8

### Scenario:

- use apt cookbook 2.9.2
- add another repo (see code in exception)
- works with compat_resource (12.9.1)
- breaks chef run when Berkshelf resolves compat_resource (12.10.1)

### Actual Result:

 Chef::Exceptions::ResourceNotFound
    ----------------------------------
    resource execute[apt-get update] is configured to notify resource execute[apt-cache gencaches] with action run, but execute[apt-cache gencaches] cannot be found in the resource collection. execute[apt-get update] is defined in /home/rmoriz/chef-solo/cookbooks-2/apt/providers/repository.rb:196:in `block in class_from_file'
    
    Cookbook Trace:
    ---------------
    /home/rmoriz/chef-solo/cookbooks-2/compat_resource/files/lib/chef_compat/monkeypatches/chef/resource_collection.rb:45:in `find_local'
    /home/rmoriz/chef-solo/cookbooks-2/compat_resource/files/lib/chef_compat/monkeypatches/chef/resource_collection.rb:58:in `find'
    /home/rmoriz/chef-solo/cookbooks-2/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:41:in `run_action'
    
    Resource Declaration:
    ---------------------
    # In /home/rmoriz/chef-solo/cookbooks-2/xxxx-base/recipes/_backports.rb
    
      1: apt_repository 'jessie-backports' do
      2:   uri 'http://http.debian.net/debian'
      3:   distribution 'jessie-backports'
      4:   components ['main']
      5:   cache_rebuild true
      6:   action :add
      7:   only_if { node['lsb']['codename'] == 'jessie' }
      8: end
    
    Compiled Resource:
    ------------------
    # Declared in /home/rmoriz/chef-solo/cookbooks-2/xxxx-base/recipes/_backports.rb:1:in `from_file'
    
    apt_repository("jessie-backports") do
      action [:add]
      retries 0
      retry_delay 2
      default_guard_interpreter :default
      declared_type :apt_repository
      cookbook_name :"xxxx-base"
      recipe_name "_backports"
      uri "http://http.debian.net/debian"
      distribution "jessie-backports"
      components ["main"]
      cache_rebuild true
      only_if { #code block }
    end

**Comment by lamont-granquist** [comment]
confirmed its a bug, definitely due to the new 12.10.1 stuff.

**Comment by lamont-granquist** [comment]
this is most likely related to what broke:

```ruby
[2016-05-20T11:20:13-07:00] WARN: Cloning resource attributes for file[/var/lib/apt/periodic/update-success-stamp] from prior resource (CHEF-3694)
[2016-05-20T11:20:13-07:00] WARN: Previous file[/var/lib/apt/periodic/update-success-stamp]: /var/chef/cache/cookbooks/apt/recipes/default.rb:29:in `from_file'
[2016-05-20T11:20:13-07:00] WARN: Current  file[/var/lib/apt/periodic/update-success-stamp]: /var/chef/cache/cookbooks/apt/providers/repository.rb:187:in `block in class_from_file'
[2016-05-20T11:20:13-07:00] WARN: Cloning resource attributes for execute[apt-get update] from prior resource (CHEF-3694)
[2016-05-20T11:20:13-07:00] WARN: Previous execute[apt-get update]: /var/chef/cache/cookbooks/apt/recipes/default.rb:59:in `from_file'
[2016-05-20T11:20:13-07:00] WARN: Current  execute[apt-get update]: /var/chef/cache/cookbooks/apt/providers/repository.rb:196:in `block in class_from_file'
```

those are 3694 warnings coming from a sub resource collection trying to clone resources in the outer run context, which is all kinds of wrong...

**Comment by tonyflint** [comment]
This is causing us a lot of converge failures (usually with the apt 2.9.2 cookbook).
