### ISSUE TITLE
docker 509 - docker_container resources with sensitve(true) should not log their properties #509

### ISSUE THREAD

**Issue by someara** [chef-cookbooks/compat_resource#6]
Moving this over from the chef-docker repo because it properly belongs here.

One of the properties on all chef resources is `sensitive`, the [chef docs for this property](https://docs.chef.io/resources.html#properties) indicate that its purpose is to

> Ensure that sensitive resource data is not logged by the chef-client.

The reason this matters is I have containers where the environment variables contain passwords I've read from encrypted data bag items. For example:

```ruby
docker_container 'foo' do
  env 'AWS_KEY=abcdef AWS_SECRET=1234'
  sensitive true
end
```

would ignore the `sensitive` and output something like this to the log:

```
- create foo
-   set container_name               to "foo"
-   set env                          to ["AWS_KEY=abcdef AWS_SECRET=1234"]
```

That seems bad.

**Comment by chasebolt** [comment]
this is linked to https://github.com/chef/chef/pull/4054

**Comment by lamont-granquist** [comment]
got fixed in core chef and should have been merged here per @jkeiser's comment in the chef/chef#4054 ticket that the cookbook shipped with this fix
