### ISSUE TITLE
cookbook version compatible with chef 11.8.2

### ISSUE THREAD

**Issue by Puneeth-n** [chef-cookbooks/compat_resource#63]
Hi all,

Which version of the cookbook would be compatible with chef version 11.8.2? For legacy reasons, we need to stick to this chef version.

TIA

**Comment by jaybill** [comment]
Is there a reason this was closed with no comment whatsoever?

**Comment by sarikav1986** [comment]
I am also getting similar error while running chef 11.8.2

================================================================================
Recipe Compile Error in /var/chef/cache/cookbooks/compat_resource/libraries/autoload.rb
================================================================================


RuntimeError
------------
This resource is written with Chef 12.5 custom resources, and requires at least Chef 12.0 used with the compat_resource cookbook, it will not work with Chef 11.x clients, and those users must pin their cookbooks to older versions or upgrade.

**Comment by nelsonenzo** [comment]
Same here :(

**Comment by Puneeth-n** [comment]
@jaybill Guys, read the `README`. If you are using `chef 11.x` and somehow depending on `compat_resource` it definitely means one of your cookbooks that you use is for `chef 12.x`. Find that cookbook which depends on `compat_resource` and freeze its version to the version compatible with `chef 11.x` thereby not using `compat_resource`.

**Comment by lamont-granquist** [comment]
Chef, Inc has mostly dropped Chef 11 support from community cookbooks.

If you expect to be using current up-to-date community cookbooks, you can't be using a version of chef-client which was released on December 3, 2013 and is now 3 years out of date.  You have to do the work to upgrade your infrastructure and get on a more recent chef version.
