### ISSUE TITLE
Resource notification behavior has changed between 12.9.1 -> 12.10.5; :before appears to no longer work.

### ISSUE THREAD

**Issue by tonyflint** [chef-cookbooks/compat_resource#66]
### Cookbook version
12.10.5

### Chef-client version
12.6.0 and 12.10.24

### Platform Details
Ubuntu 12.04 (box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_ubuntu-12.04_chef-provisionerless.box)

### Scenario:
The behavior of resource notification appears to have changed between compat_resource 12.9.1 and 12.10.5.

### Steps to Reproduce:

See test cookbook here: https://github.com/tonyflint/notified_resource_example

Given the recipe code:
```
# recipes/default.rb
folder_owner = nil

ruby_block "get_folder_uid" do
  block do
    folder_owner = "vagrant"
  end
  action :nothing
end

directory "/tmp/foo" do
  owner lazy { folder_owner } # lazy means that the variable value is looked up at converge vs. compile
  notifies :run, "ruby_block[get_folder_uid]", :before
end
```
In 12.9.1 the `/tmp/foo` folder would be owned by 'vagrant'.
In 12.10.5, the `get_folder_uid` resource is not notified/executed, and the folder is owned by 'root'.

### Expected Result:
Resources called with `:before` are executed prior to the calling resource.

### Actual Result:
Resources called with `:before` are not executed at all during the chef-client run.

**Comment by coderanger** [comment]
This might be related more to a shift in when the `lazy` gets evaluated. Please try with something more clear in the ruby block, like a log statement or raise an exception. Nothing in the example jumps out to me as behavior that would trigger compat requirements.

**Comment by tonyflint** [comment]
@coderanger I've updated the repo to simplify the example: https://github.com/tonyflint/notified_resource_example

It seems clearcut to me, but maybe I'm missing something. With the same recipe code, the behavior is different between which version of `compat_resource` is loaded:

```
       Recipe: notify-failure::default
         * ruby_block[get_folder_owner] action nothing (skipped due to action :nothing)
         * directory[/tmp/foo] action create
           - create new directory /tmp/foo

vs. 

       Recipe: notify-success::default
         * ruby_block[get_folder_owner] action nothing (skipped due to action :nothing)
         * directory[/tmp/foo] action create
           - Would create new directory /tmp/foo
         * ruby_block[get_folder_owner] action run[2016-06-07T21:23:09+00:00] WARN: Begin get_folder_owner ruby_block
       [2016-06-07T21:23:09+00:00] WARN: End get_folder_owner ruby_block

           - execute the ruby block get_folder_owner
         * directory[/tmp/foo] action create
           - create new directory /tmp/foo
           - change owner from '' to 'vagrant'
```

**Comment by sepek** [comment]
- seems to be related to https://github.com/chef/chef/issues/4983
- was introduced with fa16f21039adb828fdd2209762ebc2cae22271dc

I created a small test recipe myself:
```
execute 'echo_foo' do
  command 'echo foo'
  action :nothing
end

execute 'echo_bar' do
  command 'echo bar'
  action :run
  notifies :run, 'execute[echo_foo]', :before
end
```

If I call it directly it works, I think because it doesn't load any additional cookbooks like compat_resource:
```
$ chef-client -z links.rb
Assuming /root.
Starting Chef Client, version 12.8.1
resolving cookbooks for run list: []
Synchronizing Cookbooks:
Installing Cookbook Gems:
Compiling Cookbooks...
Converging 2 resources
Recipe: @recipe_files::/root/links.rb
  * execute[echo_foo] action nothing (skipped due to action :nothing)
  * execute[echo_bar] action run
    - Would execute echo bar
  * execute[echo_foo] action run
    - execute echo foo
  * execute[echo_bar] action run
    - execute echo bar

Running handlers:
Running handlers complete
Chef Client finished, 3/4 resources updated in 01 seconds
```
Using it in the chef-repo with -zo or the server directly doesn't do anything with "echo_foo" if this cookbook is used from the mentioned commit on:
```
  * execute[echo_foo] action nothing (skipped due to action :nothing)
  * execute[echo_bar] action run
    - execute echo bar
```

**Comment by trevorlauder** [comment]
I hit this issue as well and have confirmed that fa16f2 is the commit that breaks the `:before` timer.  If I use 6a59363 the timer works just fine.

Chef: 12.11.18
RHEL 7.2

**Comment by csghuser** [comment]
Not sure if this is related, but this new version is causing looping issues for me in cookbooks, they loop around certain sections of code forever. Way I found to fix it was adding this to my cookbook metadata files:

```
depends 'compat_resource', '= 12.9.1'
```

**Comment by Chili-Man** [comment]
@csghuser I was hitting the same issue as well and locking it down to 12.9.1 fixed it for me. I'm currently using Chef 12.4.3 on Ubuntu 14.04

**Comment by csghuser** [comment]
@Chili-Man Glad it's not just me then :-)

For reference I am using chef 12.5.1.

**Comment by gravesb** [comment]
I experienced the same looping behavior as well. It occurred on a resource that had a delayed notification. The notification was triggering immediately and would re-run the same resource indefinitely.

**Comment by tonyflint** [comment]
Can confirm, #83 fixed this. I added a new test cookbook to https://github.com/tonyflint/notified_resource_example with 12.14.1 specified in the Berksfile, and the `:before` timer again works.

Thanks!

**Comment by lamont-granquist** [comment]
yep side-effect is that compat_resource now also back ports :before notifications so that they work in e.g. 12.1.x
