### ISSUE TITLE
Recipe monkeypatch breaks chef-client when run with multiple specific recipes

### ISSUE THREAD

**Issue by christinedraper** [chef-cookbooks/compat_resource#70]
### Cookbook version

compat_resource gem 12.9.1

### Chef-client version

chef-client 12.9.1

### Platform Details

Ubuntu 14.04

### Scenario:

Run more than one specific chef-provisioning recipes using chef-client.

chef-client -z vagrant_setup.rb deploy.rb

### Steps to Reproduce:

Two recipes, first of which causes compat_resource gem to be loaded, e.g. chef provisioning recipes such as:
```
recipe1:
with_driver 'vagrant'

with_machine_options :vagrant_options => {
  'vm.box' => 'ubuntu64'
}

recipe2:
machine 'appserver'
```
```
chef-client -z recipe1.rb recipe2.rb
```

### Expected Result:

The recipes should both be run

### Actual Result:

```
ERROR: Cookbook @recipe_files not found. If you're loading @recipe_files from another cookbook, make sure you configure the dependency in your metadata
```
#### Stacktrace

```
Generated at 2016-06-06 08:55:12 -0500
Chef::Exceptions::CookbookNotFound: Cookbook @recipe_files not found. If you're loading @recipe_files from another cookbook, make sure you configure the dependency in your metadata
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.41/lib/chef/cookbook/cookbook_collection.rb:39:in `block in initialize'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/ohai-8.14.0/lib/ohai/mash.rb:77:in `yield'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/ohai-8.14.0/lib/ohai/mash.rb:77:in `default'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/ohai-8.14.0/lib/ohai/mash.rb:77:in `default'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/compat_resource-12.9.1/files/lib/chef_compat/monkeypatches/chef/recipe.rb:12:in `[]'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/compat_resource-12.9.1/files/lib/chef_compat/monkeypatches/chef/recipe.rb:12:in `new'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.41/lib/chef/run_context.rb:373:in `load_recipe_file'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.41/lib/chef/policy_builder/expand_node_object.rb:100:in `block in setup_run_context'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.41/lib/chef/policy_builder/expand_node_object.rb:99:in `each'
<snip>
```
The failure appears to be in the recipe monkeypatch on loading the second recipe, when evaluating
`run_context.cookbook_collection[cookbook_name]`. This raises an error because '@recipe_files' (which is used as the cookbook name when loading the first recipe) is not a valid cookbook. One possible fix would be to check for `Chef::Config[:specific_recipes]` in the monkeypatch.

-----

Originally raised as https://github.com/chef/chef/issues/4997

**Comment by maxivak** [comment]
I have this simple file:
```
# configure.rb

file '/tmp/my.txt' do
  content 'anything'
end

template '/tmp/my2.txt' do
  source 'my.erb'
end


### agent
# agent - setup
#cd $ROCANA_HOME
#nohup bin/rocana-agent > logs/rocana-agent.out 2> logs/rocana-agent.err &

# agent - start


```
which I run with chef-client:

```
chef-client -z configure.rb
```

It fails with error:
```
Cookbook @recipe_files not found. If you're loading @recipe_files from another cookbook, make sure you configure the dependency in your metadata
```

**Comment by elyscape** [comment]
This issue makes it 100% impossible to use chef-provisioning.

**Comment by lamont-granquist** [comment]
based on https://github.com/chef/chef-provisioning/issues/335 it seems to persist in 12.10/12.11/etc and is not a 12.3.0-specific isssue.

**Comment by lamont-granquist** [comment]
this bug has nothing to do with compat_resource and can be replicated with cheffish, chef-provisioning and compat_resource all removed and with that simple example above.

**Comment by lamont-granquist** [comment]
so @maxivak's bug is actually attempting to use a template resource with no cookbook structure -- its like trying to use a template resource with chef-apply and something we've never supported.

**Comment by lamont-granquist** [comment]
yeah this never had anything to do with this cookbook and gem and may not even be a bug, if it is a bug its probably a chef-provisioning bug.
