### ISSUE TITLE
Causes package build-essential to fail local kitchen converge

### ISSUE THREAD

**Issue by chris-sanders-dot-org** [chef-cookbooks/compat_resource#71]
### Cookbook version
12.10

### Chef-client version
Chef Development Kit Version: 0.14.25
chef-client version: 12.10.24
berks version: 4.3.3
kitchen version: 1.8.0

### Platform Details
RHEL 6.5 in local development (vagrant/kitchen).

### Scenario:
Local kitchen converge of RHEL 6.5 succeeds with version 12.9.1.  Version 12.10 results in an error when installing build-essential, it wants to install ncurses-devel, but it can't be found by yum..

### Steps to Reproduce:
Unfortunately, I'm really not sure.  For us, not having the compat_resource cookbook pinned to 12.9.1 results in the error.  We have in our run list a recipe that configures custom yum repositories.

Could it be that compat_resource expects a valid yum repo immediately, and before any custom yum repos can be configured by our yum cookbook?  When the converge fails, it is prior to our custom yum entries being added to yum.repos.d.

### Expected Result:
Kitchen converge should be successful, with custom yum repos configured.

### Actual Result:
Kitchen converge fails trying to install ncurses-devel.  Investigation of the yum.repos.d directory shows that our custom yum repos are not configured at time of error.

### Full Error Output:
https://gist.github.com/chris-sanders-dot-org/89faaec4000b49310933739dd4c1f79d

Thanks,
Chris

**Comment by tas50** [comment]
@chris-sanders-dot-org Can you try pulling in the latest 12.10 compat_resource to see if this is still occurring. We've made some updates to the cookbook.

**Comment by lamont-granquist** [comment]
You'd probably need to push a cookbook up to git with a .kitchen.yml that showed the error in order to replicate it.  This error doesn't really make any sense at all.

**Comment by lamont-granquist** [comment]
yeah can't replicate it and can't see how this was due to compat_resource.  looks like the code which picks out the code fragment was a little buggy and showed the compat_resource code instead of the user code -- which might actually have been fixed in 12.14.0, but this looks more like some issue in how the yum package provider is being used or just with out of date yum caches
