### ISSUE TITLE
Delayed resources called more than once with Chef <= 12.4

### ISSUE THREAD

**Issue by wwilfinger** [chef-cookbooks/compat_resource#87]
### Cookbook version
compat_resource 12.10.7

### Chef-client version
Initially seen with Chef 12.4.1
Test-kitchen shows its an issue with 12.0.x through and including
12.4.x. 12.5.x and above seem to be fine.

### Platform Details
CentOS 6.7 initially. Test-kitchen with Ubuntu 14.04

### Scenario:
* A cookbook dependency on compat_resource
* A delayed resource notification
* A call to a <12.5 style LWRP that sets use_inline_resources.

The delayed resource is invoked twice. Once at the end of the LWRP and
once at the end of the Chef run.

Remove the dependency on compat_resource and the delayed resource
is invoked only once at the end of the Chef run, which is what I expect.

In my specific real world example (not shown), the delayed resource is
something that I can only have called once per Chef run.

### Steps to Reproduce:
I have a test-kitchen set up example here:
https://github.com/wwilfinger/multi_delayed_call_mwe

In short

```
# metadata.rb
depends 'compat_resource'

# providers/default.rb
use_inline_resources

action :run do
end

# resources/default.rb
actions :run
default_action :run

attribute :name, :kind_of => String, :name_attribute => true

# recipes/default.rb

ruby_block "notifies_delayed_ruby_block" do
  block do
    Chef::Log.info "Notify a delayed resource"
  end
  action :run
  notifies :run, 'ruby_block[delayed_ruby_block]', :delayed
end

multi_delayed_call "custom_resource" do
end

ruby_block "delayed_ruby_block" do
  block do
    Chef::Log.info "I'm a delayed resource"
  end
  action :nothing
end
```

### Expected Result:
Delayed resource should be invoked only once.

### Actual Result:
Delayed resource is invoked once per LWRP with use_inline_resources.

---

I have all the Chef 12 releases from the [Chef changelog](https://github.com/chef/chef/blob/master/CHANGELOG.md)
in the kitchen.yml. When depending on compat_resource, 12.0-12.4 fail,
12.5 and above are fine. If I comment out the depends compat_resource,
all Chef versions work.

Thanks for your time!

**Comment by lamont-granquist** [comment]
TK setup is useful -- confirmed this still fails with 12.14.0 release of this cookbook

**Comment by lamont-granquist** [comment]
- still an issue in the 12.14.2 release of this cookbook.
- the chef-solo provisioner in TK doesn't matter, it still fails with chef-zero
- the use_inline_resource LWRP is important -- a custom resource doesn't fail in the same way

**Comment by r2oro** [comment]
I have observed infinite recursion upon triggering delayed resource on Windows Chef 12.3

The recipe is:

```
windows_task 'reinstall-chef-client' do
  command command
  run_level :highest
  frequency :once
  start_time lazy { (Time.now + (node['hc_chef_client']['restart_delay'] * 60)).localtime.strftime('%H:%M') }
  action :nothing
  notifies :write, 'log[Scheduled reinstall-chef-client]', :immediately
end

log 'Scheduled reinstall-chef-client' do
  message 'Scheduled reinstall-chef-client'
  level :info
  action :nothing
end

template "#{Chef::Config[:file_cache_path]}/reinstall_chef.ps1" do
  source 'reinstall_chef.ps1.erb'
  variables(
    msi_path: "#{Chef::Config[:file_cache_path]}\\#{base_package_filename}",
    msi_log: "#{node['chef_client']['log_dir']}\\#{base_package_filename}.log"
  )
  notifies :create, 'windows_task[reinstall-chef-client]', :delayed
end
```

It converges as below:

```
Starting Chef Client, version 12.3.0
resolving cookbooks for run list: ["test_inf_resursion"]
Synchronizing Cookbooks:
  - chef_handler
  - powershell
  - windows
  - ms_dotnet
  - test_inf_resursion
  - compat_resource
Compiling Cookbooks...
[2016-09-16T16:35:58+00:00] WARN: Cloning resource attributes for windows_task[reinstall-chef-client] from prior resourc
e (CHEF-3694)
[2016-09-16T16:35:58+00:00] WARN: Previous windows_task[reinstall-chef-client]: C:/chef/cache/cookbooks/test_inf_resursi
on/recipes/default.rb:9:in `from_file'
[2016-09-16T16:35:58+00:00] WARN: Current  windows_task[reinstall-chef-client]: C:/chef/cache/cookbooks/test_inf_resursi
on/recipes/create.rb:18:in `from_file'
Converging 6 resources

...

 * windows_task[reinstall-chef-client] action create
   * windows_task[reinstall-chef-client] action create
     * windows_task[reinstall-chef-client] action create
       * windows_task[reinstall-chef-client] action create
         * windows_task[reinstall-chef-client] action create
           * windows_task[reinstall-chef-client] action create
             * windows_task[reinstall-chef-client] action create
               * windows_task[reinstall-chef-client] action create
                 * windows_task[reinstall-chef-client] action create
                   * windows_task[reinstall-chef-client] action create
                     * windows_task[reinstall-chef-client] action create
                       * windows_task[reinstall-chef-client] action create
                         * windows_task[reinstall-chef-client] action create
                           * windows_task[reinstall-chef-client] action create
                             * windows_task[reinstall-chef-client] action create
```
