### ISSUE TITLE
updated run_context initializer calls Chef::Node#set_cookbook_attribute which does not exist in 12.3.0

### ISSUE THREAD

**Issue by stevie911** [chef-cookbooks/compat_resource#92]
### Cookbook version
12.13.38

### Chef-client version
12.3.0

### Platform Details
RHEL 6.8,  6.6

### Scenario:
When 12.13.38 cookbook is being used we get an error on an execute block

DEBUG: Re-raising exception: NoMethodError - execute[setup password expiration for rundeck] (wdprt_sece_base::users line 21) had an error: NoMethodError: Undefined method or attribute `set_cookbook_attribute' on `node'
 /opt/chef/embedded/apps/chef/lib/chef/node/attribute.rb:468:in `method_missing'
 /opt/chef/embedded/apps/chef/lib/chef/node.rb:229:in `method_missing'

### Steps to Reproduce:
It seems that execute block in multiple recipes in the run_list cause this error

### Expected Result:
Run through to completion without errors

### Actual Result:
chef-client exits out at the execute block with 

  * execute[setup password expiration for rundeck] action run

    ================================================================================
    Error executing action `run` on resource 'execute[setup password expiration for rundeck]'
    ================================================================================

    NoMethodError
    -------------
    Undefined method or attribute `set_cookbook_attribute' on `node'

    Cookbook Trace:
    ---------------
    /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/run_context.rb:165:in `initialize'
    /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:78:in `run_action'
    /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `block (2 levels) in converge'
    /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `each'
    /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `block in converge'
    /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:105:in `converge'

Running handlers:
[2016-08-25T11:32:21-04:00] ERROR: Running exception handlers
Running handlers complete
[2016-08-25T11:32:21-04:00] ERROR: Exception handlers complete
[2016-08-25T11:32:21-04:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
Chef Client failed. 4 resources updated in 5.373306389 seconds
[2016-08-25T11:32:21-04:00] ERROR: execute[setup password expiration for rundeck] had an error: NoMethodError: Undefined method or attribute `set_cookbook_attribute' on `node'
[2016-08-25T11:32:21-04:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)

Rolling back to 12.10.7 fixes the issue.

**Comment by lamont-granquist** [comment]
/var/chef/cache/chef-stacktrace.out contents along with the actual code you're running would also be useful.

**Comment by lamont-granquist** [comment]
this is called in the initializer of the run_context, it has nothing to do with execute resources that i can see...

**Comment by stevie911** [comment]
Here is the full stack trace

`Generated at 2016-08-25 13:17:15 -0400
NoMethodError: execute[setup password expiration for rundeck] (wdprt_sece_base::users line 21) had an error: NoMethodError: Undefined method or attribute `set_cookbook_attribute' on `node'
/opt/chef/embedded/apps/chef/lib/chef/node/attribute.rb:468:in `method_missing'
/opt/chef/embedded/apps/chef/lib/chef/node.rb:229:in `method_missing'
/var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/run_context.rb:165:in `initialize'
/opt/chef/embedded/apps/chef/lib/chef/guard_interpreter/resource_guard_interpreter.rb:96:in `new'
/opt/chef/embedded/apps/chef/lib/chef/guard_interpreter/resource_guard_interpreter.rb:96:in `get_interpreter_resource'
/opt/chef/embedded/apps/chef/lib/chef/guard_interpreter/resource_guard_interpreter.rb:28:in `initialize'
/opt/chef/embedded/apps/chef/lib/chef/guard_interpreter.rb:28:in `new'
/opt/chef/embedded/apps/chef/lib/chef/guard_interpreter.rb:28:in `for_resource'
/opt/chef/embedded/apps/chef/lib/chef/resource/conditional.rb:59:in `configure'
/opt/chef/embedded/apps/chef/lib/chef/resource/conditional.rb:82:in `continue?'
/opt/chef/embedded/apps/chef/lib/chef/resource.rb:1074:in `block in should_skip?'
/opt/chef/embedded/apps/chef/lib/chef/resource.rb:1073:in `each'
/opt/chef/embedded/apps/chef/lib/chef/resource.rb:1073:in `find'
/opt/chef/embedded/apps/chef/lib/chef/resource.rb:1073:in `should_skip?'
/opt/chef/embedded/apps/chef/lib/chef/resource.rb:561:in `run_action'
/var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:78:in `run_action'
/var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `block (2 levels) in converge'
/var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `each'
/var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `block in converge'
/opt/chef/embedded/apps/chef/lib/chef/resource_collection/resource_list.rb:83:in `block in execute_each_resource'
/opt/chef/embedded/apps/chef/lib/chef/resource_collection/stepable_iterator.rb:116:in `call'
/opt/chef/embedded/apps/chef/lib/chef/resource_collection/stepable_iterator.rb:116:in `call_iterator_block'
/opt/chef/embedded/apps/chef/lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
/opt/chef/embedded/apps/chef/lib/chef/resource_collection/stepable_iterator.rb:104:in `iterate'
/opt/chef/embedded/apps/chef/lib/chef/resource_collection/stepable_iterator.rb:55:in `each_with_index'
/opt/chef/embedded/apps/chef/lib/chef/resource_collection/resource_list.rb:81:in `execute_each_resource'
/var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:105:in `converge'
/opt/chef/embedded/apps/chef/lib/chef/client.rb:339:in `block in converge'
/opt/chef/embedded/apps/chef/lib/chef/client.rb:334:in `catch'
/opt/chef/embedded/apps/chef/lib/chef/client.rb:334:in `converge'
/opt/chef/embedded/apps/chef/lib/chef/client.rb:353:in `converge_and_save'
/opt/chef/embedded/apps/chef/lib/chef/client.rb:457:in `run'
/opt/chef/embedded/apps/chef/lib/chef/application.rb:271:in `block in fork_chef_client'
/opt/chef/embedded/apps/chef/lib/chef/application.rb:259:in `fork'
/opt/chef/embedded/apps/chef/lib/chef/application.rb:259:in `fork_chef_client'
/opt/chef/embedded/apps/chef/lib/chef/application.rb:225:in `block in run_chef_client'
/opt/chef/embedded/apps/chef/lib/chef/local_mode.rb:39:in `with_server_connectivity'
/opt/chef/embedded/apps/chef/lib/chef/application.rb:213:in `run_chef_client'
/opt/chef/embedded/apps/chef/lib/chef/application/client.rb:402:in `block in interval_run_chef_client'
/opt/chef/embedded/apps/chef/lib/chef/application/client.rb:392:in `loop'
/opt/chef/embedded/apps/chef/lib/chef/application/client.rb:392:in `interval_run_chef_client'
/opt/chef/embedded/apps/chef/lib/chef/application/client.rb:382:in `run_application'
/opt/chef/embedded/apps/chef/lib/chef/application.rb:60:in `run'
/opt/chef/embedded/apps/chef/bin/chef-client:26:in `<top (required)>'
/usr/bin/chef-client:51:in `load'
/usr/bin/chef-client:51:in `<main>'`

**Comment by lamont-granquist** [comment]
TIL the guard interpreter stuff creates its own run_context.  So this most likely happens with an execute resource, with a guard.  Although it should also happen with any sub-run-context created by a use_inline_resources style provider as well...

**Comment by stevie911** [comment]
The one we have does have a guard.

`     21: execute 'setup password expiration for rundeck' do
     22:   command 'chage -I -1 -m 0 -M 90 -E -1 rundeck'
     23:   action :run
     24:   not_if 'chage -l rundeck | grep 90'
     25: end
     26:`
