### ISSUE TITLE
Subscription broken with 12.13.37 and higher

### ISSUE THREAD

**Issue by bcurnow** [chef-cookbooks/compat_resource#99]
### Cookbook version
12.13.37, 12.13.38, 12.14.0, 12.14.1

### Chef-client version
12.3.0

### Platform Details
Red Hat Enterprise Linux 6.6

### Scenario:
Trying to subscribe to a cookbook_file resource with an execute or log block

### Steps to Reproduce:
Create a cookbook with the following metadata
```
name             'test-subscribes'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Tests Subscription'
long_description 'Tests Subscription'
version          '0.1.0'

depends 'compat_resource'
```

Then create a recipe:
```
file '/var/tmp/test.file' do
  action :delete
end

r = cookbook_file 'test_file' do
      source "test.file"
	    path "/var/tmp/test.file"
    end

log 'Log if the cookbook_file was updated' do
  message lazy { "Was the cookbook_file updated?: #{r.updated}" }
  level :warn
end


execute 'cool command' do
  command 'echo "I\'m running!"'
  subscribes :run, 'cookbook_file[test_file]', :immediately
  action :nothing
end

log 'cool log output' do
  subscribes :write, 'cookbook_file[test_file]', :immediately
  action :nothing
end
```

The test.file is a simple text file with the content "This is a test file"

Execute that cookbook, note that the execute and log resources with subscription don't execute at all.

Comment out `depends 'compat_resource'` from metadata and run again, works!

### Expected Result:
Expect that the subscription fires and execute and log actually run.

### Actual Result:
Despite a successful update by cookbook_file, the execute and log resources don't fire.

This looks like it is related to the following code added to files/lib/chef_compat/copied_from_chef/chef/dsl/declare_resource.rb in version 12.13.37:

```
+        run_context.resource_collection.delete("#{type}[#{name}]").tap do |resource|
+          # Purge any pending notifications too. This will not raise an exception
+          # if there are no notifications.
+          if resource
+            run_context.before_notification_collection.delete(resource.declared_key)
+            run_context.immediate_notification_collection.delete(resource.declared_key)
+            run_context.delayed_notification_collection.delete(resource.declared_key)
+          end
+        end
```

**Comment by drwahl** [comment]
Confirming that I am also able to reproduce this error.

**Comment by gravesb** [comment]
Possibly related to #66?
